[RND-1054] ne-storage와 atlas 데이터 계보 연동
nexr/ceph pull request #9
Opened 2021-11-22 05:50 UTC by bgy217

* ne-storage의 오브젝트 스토어의 데이터 입출력 내역이 그래프로 보이도록 atlas 데이터 계보로 요청 처리 내역을 보내도록 한다.
* rokku의 기능 일부를 ne-storage로 가져오는 것으로 시작한다.

2021-11-23 09:40 UTC, minyk requested changes
java 가 아니라서 이 정도만 뭔지 알아볼 수 있네요

2021-11-23 09:40 UTC, minyk commented on src/common/legacy_config_opts.h
> +OPTION(rgw_lineage_atlas_rest_version, OPT_STR) // Atlas url api version
굳이 legacy api 를 지원할 필요가 있을까요? REST API 주소 옵션들을 하나로 합치는 게 낫지 않을까 합니다.

2021-11-23 09:40 UTC, minyk commented on src/common/legacy_config_opts.h
> +OPTION(rgw_lineage_atlas_rest_url_prefix, OPT_STR) // rgw_lineage_atlas_url_prefix
`/api/atlas` 는 거의 변경되지 않을 거 같은데, atlas 쪽에 설정할 수 있는 지점이 있나요?

2021-11-30 03:05 UTC, bgy217 commented on src/common/legacy_config_opts.h
> +OPTION(rgw_lineage_atlas_rest_version, OPT_STR) // Atlas url api version
여기에 넣어야 추후에 사용하기 편하게 되어 있어서 넣었습니다.
legacy 지원 측면이라기 보다는 그냥 사용성을 위해서 추가한 코드라고 보시면 될것 같습니다.

2021-11-30 03:06 UTC, bgy217 commented on src/common/legacy_config_opts.h
> +OPTION(rgw_lineage_atlas_rest_url_prefix, OPT_STR) // rgw_lineage_atlas_url_prefix
그걸 잘 몰라서 일단 넣어놨는데 조사를 해보고 변경이 안되는 값이라면 설정에서 빼는게 낫겠네요

2021-12-23 00:33 UTC, bgy217 commented on src/common/legacy_config_opts.h
> +OPTION(rgw_lineage_atlas_rest_url_prefix, OPT_STR) // rgw_lineage_atlas_url_prefix
찾아보니 변경이 안되는 값이네요. 해당 설정을 빼고 개발하겠습니다.

2021-12-23 01:58 UTC, bgy217 commented on src/common/legacy_config_opts.h
> +OPTION(rgw_lineage_atlas_rest_version, OPT_STR) // Atlas url api version
지금보니 제가 잘못 이해했군요.
현재 v2의 atlas API를 기준으로 개발되어 있고 API의 버전만 바꾼다고 해서 호환될 것 같지 않으니
말씀대로 api 버전은 v2로 고정하는 것이 좋겠습니다.

2021-12-28 01:21 UTC, bgy217 commented on src/common/legacy_config_opts.h
> +OPTION(rgw_lineage_atlas_rest_version, OPT_STR) // Atlas url api version
5223c1e 에서 반영했습니다.

2021-12-28 01:21 UTC, bgy217 commented on src/common/legacy_config_opts.h
> +OPTION(rgw_lineage_atlas_rest_url_prefix, OPT_STR) // rgw_lineage_atlas_url_prefix
5223c1e 에서 반영했습니다.

2021-12-28 01:22 UTC, merged